<?php
require_once('page.php');
sleep(300);
require_once('file.php');
sleep(300);
require_once('transform.php');
sleep(300);
require_once('txt_to_json_convert.php');
sleep(300);
require_once('file_to_db.php');
